config/routes.rb
Rails.application.routes.draw do
  resource :quick_registration, only: [:new, :create]
  resource :full_registration, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/full_registrations_controller.rb
class FullRegistrationsController < ApplicationController
  def new
    @user = FullRegistration.new
  end

  def create
    @user = FullRegistration.new(user_params)

    if @user.valid?
      User.create!(@user.persistable_attributes)
      redirect_to new_quick_registration_path, notice: "You have been registered"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(*FullRegistration::Attributes)
  end
end

app/controllers/quick_registrations_controller.rb
class QuickRegistrationsController < ApplicationController
  def new
    @user = QuickRegistration.new
  end

  def create
    @user = QuickRegistration.new(user_params)

    if @user.valid?
      User.create!(@user.persistable_attributes)
      redirect_to new_quick_registration_path, notice: "You have been registered"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(*QuickRegistration::Attributes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/full_registrations/new.html.erb
<%= form_for @user, url: full_registration_path, as: :user do |f| %>
  <%= f.text_field :email %>
  <%= f.object.errors_for :email %>

  <%= f.text_field :password %>
  <%= f.object.errors_for :password %>

  <%= f.text_field :password_confirmation %>
  <%= f.object.errors_for :password_confirmation %>

  <%= f.text_field :date_of_birth %>
  <%= f.object.errors_for :date_of_birth %>

  <%= f.check_box :terms_accepted %>
  <%= f.object.errors_for :terms_accepted %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormObjectDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quick_registrations/new.html.erb
<%= form_for @user, url: quick_registration_path, as: :user do |f| %>
  <%= f.text_field :email %>
  <%= f.object.errors_for :email %>

  <%= f.text_field :password %>
  <%= f.object.errors_for :password %>

  <%= f.text_field :password_confirmation %>
  <%= f.object.errors_for :password_confirmation %>
<% end %>